
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: tb_10_compradores
    description: "Retorna os top 10 compradores da vase"
    columns:
      - name: vendas_totais
        description: "Vendas totais por comprador"
        tests:
          - nao_negativo
          - not_null